unified dockerfiles
DefangLabs/samples pull request #169
Opened 2024-08-08 23:22 UTC by Chrisyhjiang

This PR is designed to make all the base image of node js smaples to be debian:bookworm-slim.

2024-08-08 23:23 UTC, Chrisyhjiang commented
Closes #159

2024-08-15 21:51 UTC, raphaeltm requested changes
Should use `bookworm-slim` tag but from the official `node` image, not from the debian image.

2024-08-19 23:39 UTC, lionello requested changes

2024-08-19 23:39 UTC, lionello commented on samples/angular-express/backend/Dockerfile
> +FROM debian:bookworm-slim
[22-bookworm-slim](https://github.com/nodejs/docker-node/blob/c0cfa23e26d75f1f679fd6626a29a27ec5274db3/22/bookworm-slim/Dockerfile)

2024-08-19 23:53 UTC, lionello requested changes

2024-08-19 23:53 UTC, lionello commented on samples/angular-express/backend/Dockerfile
> +FROM node:bookworm-slim
This is better! But we should pick a specific version of Node. Previous sample was using v20, so this should be `20-bookworm-slim`

2024-08-20 18:31 UTC, Chrisyhjiang commented on samples/angular-express/backend/Dockerfile
> +FROM node:bookworm-slim
finished

2024-08-20 23:43 UTC, lionello approved these changes

2024-08-20 23:57 UTC, merged