create healthcheck url for samples
DefangLabs/samples pull request #190
Opened 2024-09-15 12:06 UTC by edisonqu

2024-09-15 12:13 UTC, lionello commented on samples/nextjs/compose.yaml
> +
```suggestion
```

2024-09-19 00:47 UTC, raphaeltm requested changes

2024-09-19 00:47 UTC, raphaeltm commented on samples/nextjs/compose.yaml
> +      test: wget -q --spider http://localhost:3000/api/health || exit 1
@edisonqu looks like your pinging `/api/health` but your `route.ts` file is just at `/api`. You'll need to add a `health` dir and move it in there.

2024-10-23 22:10 UTC, raphaeltm approved these changes

2024-10-23 22:11 UTC, merged